//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthClinic
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISEASES
    {
        public DISEASES()
        {
            this.DISEASES_SYMPTOMS = new HashSet<DISEASES_SYMPTOMS>();
        }
    
        public int ID_DISEASE { get; set; }
        public string DISEASE { get; set; }
    
        public virtual ICollection<DISEASES_SYMPTOMS> DISEASES_SYMPTOMS { get; set; }
    }
}
