//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthClinic
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISEASES_SYMPTOMS
    {
        public int ID_DISEASE_SYMPTOM { get; set; }
        public int ID_DISEASE { get; set; }
        public int ID_SYMPTOM { get; set; }
    
        public virtual DISEASES DISEASES { get; set; }
        public virtual SYMPTOMS SYMPTOMS { get; set; }
    }
}
