//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthClinic
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HealthClinicEntities : DbContext
    {
        public HealthClinicEntities()
            : base("name=HealthClinicEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DISEASES> DISEASES { get; set; }
        public DbSet<DISEASES_SYMPTOMS> DISEASES_SYMPTOMS { get; set; }
        public DbSet<INVOICE> INVOICE { get; set; }
        public DbSet<MEDICINE> MEDICINE { get; set; }
        public DbSet<NOTICE_BOARD> NOTICE_BOARD { get; set; }
        public DbSet<RIGHT> RIGHT { get; set; }
        public DbSet<SHIFT> SHIFT { get; set; }
        public DbSet<SYMPTOMS> SYMPTOMS { get; set; }
        public DbSet<SCHEDULE> SCHEDULE { get; set; }
        public DbSet<APPOINTMENTS> APPOINTMENTS { get; set; }
        public DbSet<USER> USER { get; set; }
    }
}
