//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthClinic
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVOICE
    {
        public int ID_INVOICE { get; set; }
        public string SUPPLIER_NAME { get; set; }
        public System.DateTime BILLING_DATE { get; set; }
        public System.DateTime REGISTRATION_DATE { get; set; }
    }
}
