//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthClinic
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDICINE
    {
        public int ID_MEDICINE { get; set; }
        public string MEDICINE_NAME { get; set; }
        public int QUANTITY { get; set; }
        public System.DateTime LAST_BILLING { get; set; }
    }
}
