//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthClinic
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTICE_BOARD
    {
        public int ID_NOTICE { get; set; }
        public string NOTICE { get; set; }
        public System.DateTime DATE_NOTICE { get; set; }
        public string ADDED_BY { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
