//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthClinic
{
    using System;
    using System.Collections.Generic;
    
    public partial class RIGHT
    {
        public RIGHT()
        {
            this.USER = new HashSet<USER>();
        }
    
        public int ID_RIGHT { get; set; }
        public string RIGHT_NAME { get; set; }
    
        public virtual ICollection<USER> USER { get; set; }
    }
}
