//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthClinic
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHIFT
    {
        public SHIFT()
        {
            this.SCHEDULE = new HashSet<SCHEDULE>();
        }
    
        public int ID_SHIFT { get; set; }
        public string SHIFT_START { get; set; }
        public string SHIFT_END { get; set; }
    
        public virtual ICollection<SCHEDULE> SCHEDULE { get; set; }
    }
}
