//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthClinic
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public USER()
        {
            this.APPOINTMENTS = new HashSet<APPOINTMENTS>();
            this.NOTICE_BOARD = new HashSet<NOTICE_BOARD>();
            this.SCHEDULE = new HashSet<SCHEDULE>();
            this.SCHEDULE1 = new HashSet<SCHEDULE>();
        }
    
        public string USERNAME { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public int ID_RIGHT { get; set; }
        public string PASSWORD { get; set; }
    
        public virtual ICollection<APPOINTMENTS> APPOINTMENTS { get; set; }
        public virtual ICollection<NOTICE_BOARD> NOTICE_BOARD { get; set; }
        public virtual RIGHT RIGHT { get; set; }
        public virtual ICollection<SCHEDULE> SCHEDULE { get; set; }
        public virtual ICollection<SCHEDULE> SCHEDULE1 { get; set; }
    }
}
